
SOCIAL_AUTH_TWITTER_KEY = 'TGTMvX9OxeWECWbKECbo2u24L'
SOCIAL_AUTH_TWITTER_SECRET = 'VXuLBOe0CW4ZIPhcVGlEmzld70q7WAg5a09wfgG21WAFYnxfab'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/dashboard/'
SOCIAL_AUTH_LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
